fmnist: &base_fmnist_config
  dataset_name: fmnist
  img_size: 28
  channel: 1
  n_classes: 10 
  latent_dim: 100
  lr: 0.0001
  b1: 0.5
  b2: 0.999
  n_epochs: 120
  num_distill_epochs: 120
  batch_size: 64
  sample_interval: 800

cifar10: &base_cifar10 
  dataset_name: cifar10
  img_size: 32
  channel: 3 
  n_classes: 10 
  latent_dim: 32
  lr: 0.0001
  b1: 0.5
  b2: 0.999
  n_epochs: 200
  num_distill_epochs: 200
  batch_size: 64
  sample_interval: 800

dim_fmnist:  
  <<: *base_fmnist_config
  d_lambda: 0.01

dim_cifar10: 
  <<: *base_cifar10
  d_lambda: 0.01

dcm_fmnist: 
  <<: *base_fmnist_config
  gamma: 0.01
  augment: True

dcm_cifar10: 
  <<: *base_cifar10
  gamma: 0.01
  augment: True
