fmnist: &base_fmnist_config
  dataset_name: fmnist
  img_size: 28
  channel: 1
  n_classes: 10 
  latent_dim: 100
  lr: 0.000005
  lr_eval_net: 0.01
  momentum: 0.9
  weight_decay: 0.0005
  epochs_match_train: 16
  n_epochs: 120
  gan_epochs: 120
  num_distill_epochs: 300
  batch_size: 100
  sample_interval: 800

cifar10: &base_cifar10 
  dataset_name: cifar10
  img_size: 32
  channel: 3 
  n_classes: 10 
  lr_eval_net: 0.01
  momentum: 0.9
  weight_decay: 0.0005
  epochs_match_train: 16
  latent_dim: 32
  lr: 0.000005
  n_epochs: 200
  gan_epochs: 120
  num_distill_epochs: 500
  batch_size: 100
  sample_interval: 800

dim_fmnist:  
  <<: *base_fmnist_config
  d_lambda: 0.01

dim_cifar10: 
  <<: *base_cifar10
  d_lambda: 0.01

dcm_fmnist: 
  <<: *base_fmnist_config
  gamma: 0.01
  augment: True

dcm_cifar10: 
  <<: *base_cifar10
  gamma: 0.01
  augment: True
